/* Suya Menús UI. API can be injected with window.SUYA_API_BASE by host app. */
import { safeImageUrl } from './security.js';
const API=window.SUYA_API_BASE||'';const state={menu:null,dishes:[],promos:[],cart:[]};
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
async function api(path,opts={}){if(!API)throw Error('API no configurada');const r=await fetch(API+path,{credentials:'include',headers:{'Content-Type':'application/json',...(opts.headers||{})},...opts});if(!r.ok)throw Error((await r.text())||`HTTP ${r.status}`);return r.status===204?null:r.json()}
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2200)}
// Image values pass through safeImageUrl(d.imageUrl) before entering CSS.
function renderPublic(){const m=state.menu||{};$('#restaurantName').textContent=m.name||'Tu restaurante';$('#restaurantMeta').textContent=m.description||'Configura tu menú digital';$('#emptyMenu').classList.toggle('hidden',state.dishes.length>0);const cats=['Todos',...new Set(state.dishes.map(d=>d.category).filter(Boolean))];$('#categories').innerHTML=cats.map((c,i)=>`<button class="${i?'':'active'}" data-cat="${esc(c)}">${esc(c)}</button>`).join('');renderDishes();if(m.logoUrl)$('#logo').style.backgroundImage=`url("${m.logoUrl}")`;if(m.coverUrl){const cover=$('#cover');cover.style.backgroundImage=`url("${m.coverUrl}")`;cover.textContent=''}if(m.primaryColor)document.documentElement.style.setProperty('--orange',m.primaryColor)}
function renderDishes(cat='Todos'){const q=($('#dishSearch').value||'').toLowerCase();const ds=state.dishes.filter(d=>d.available!==false&&(cat==='Todos'||d.category===cat)&&(!q||`${d.name} ${d.description}`.toLowerCase().includes(q)));$('#dishList').innerHTML=ds.map(d=>{const image=safeImageUrl(d.imageUrl,location.href);return `<article class="dish-card"><div class="dish-image" ${image?`style="background-image:url('${esc(image)}');background-size:cover"`:''}>${image?'': '🍽'}</div><div><h3>${esc(d.name)}</h3><p>${esc(d.description||'')}</p><span class="dish-price">S/ ${Number(d.price||0).toFixed(2)}</span></div><button class="add-btn" data-id="${esc(d.id)}" aria-label="Añadir ${esc(d.name)}">＋</button></article>`}).join('')||'<p class="subtle">No encontramos platos publicados.</p>'}
let renderAdmin=()=>{const dl=$('#dishAdminList');dl.innerHTML=state.dishes.length?state.dishes.map(d=>`<div class="dish-admin"><div class="dish-image">🍽</div><div><strong>${esc(d.name)}</strong><small>S/ ${Number(d.price||0).toFixed(2)} · ${esc(d.category||'Sin categoría')}</small></div><label class="switch"><input type="checkbox" data-dish="${esc(d.id)}" ${d.available!==false?'checked':''}><span></span></label></div>`).join(''):'<div class="empty-state compact"><span>＋</span><h3>Aún no hay platos</h3><p>Crea el primer plato para publicarlo.</p></div>';const pl=$('#promoList');pl.innerHTML=state.promos.length?state.promos.map(p=>`<div class="promo-card"><div class="promo-icon">%</div><div><strong>${esc(p.name)}</strong><p>${esc(p.code||'Sin cupón')}</p></div></div>`).join(''):'<div class="empty-state compact"><span>%</span><h3>Sin promociones</h3><p>Las promociones aparecerán aquí.</p></div>';$('#nameInput').value=state.menu?.name||'';$('#metaInput').value=state.menu?.description||'';$('#qrText').textContent=state.menu?.slug?location.origin+'/menu/'+state.menu.slug:'Publica tu menú para generar enlace'};
async function load(){try{const d=await api('/public/menu');state.menu=d.menu||d;state.dishes=d.dishes||[];state.promos=d.promos||[];renderPublic()}catch{const local=JSON.parse(localStorage.getItem('suya-menu-state')||'null');if(local){state.menu=local.menu;state.dishes=local.dishes||[];state.promos=local.promos||[]}renderPublic();if(API)toast('No se pudo cargar el menú')}}
function persist(){localStorage.setItem('suya-menu-state',JSON.stringify({menu:state.menu,dishes:state.dishes,promos:state.promos}))}
$('#adminToggle').onclick=()=>{if(!$('#adminView').classList.contains('hidden')){$('#adminView').classList.add('hidden');$('#publicView').classList.remove('hidden');return}if(sessionStorage.getItem('suya_session'))openAdmin();else $('#loginDialog').showModal()};$('#closeLogin').onclick=()=>$('#loginDialog').close();$('#loginForm').onsubmit=async e=>{e.preventDefault();try{await api('/auth/login',{method:'POST',body:JSON.stringify({email:$('#emailInput').value,password:$('#passwordInput').value})});sessionStorage.setItem('suya_session','1');$('#loginDialog').close();openAdmin()}catch{$('#loginError').textContent=API?'Correo o contraseña incorrectos.':'Conecta backend Suya para iniciar sesión.'}};
function openAdmin(){$('#publicView').classList.add('hidden');$('#adminView').classList.remove('hidden');renderAdmin();loadAdmin()};async function loadAdmin(){try{const d=await api('/admin/menu');state.menu=d.menu||d;state.dishes=d.dishes||[];state.promos=d.promos||[];renderAdmin();renderPublic()}catch{if(API)toast('No se pudo cargar panel')}}$('#logoutBtn').onclick=async()=>{try{if(API)await api('/auth/logout',{method:'POST'})}finally{sessionStorage.removeItem('suya_session');$('#adminView').classList.add('hidden');$('#publicView').classList.remove('hidden')}};
document.querySelector('.admin-nav').onclick=e=>{if(e.target.tagName!=='BUTTON')return;document.querySelectorAll('.admin-nav button').forEach(b=>b.classList.remove('active'));e.target.classList.add('active');document.querySelectorAll('.admin-panel').forEach(p=>p.classList.add('hidden'));$('#'+e.target.dataset.panel).classList.remove('hidden')};$('#dishSearch').oninput=()=>renderDishes(document.querySelector('.categories .active')?.dataset.cat||'Todos');$('#categories').onclick=e=>{if(e.target.tagName==='BUTTON'){document.querySelectorAll('#categories button').forEach(b=>b.classList.remove('active'));e.target.classList.add('active');renderDishes(e.target.dataset.cat)}};$('#dishList').onclick=e=>{const id=e.target.dataset.id;if(!id)return;const d=state.dishes.find(x=>x.id===id);state.cart.push(d);$('#cartCount').textContent=state.cart.length;$('#cartTotal').textContent='S/ '+state.cart.reduce((n,x)=>n+Number(x.price||0),0).toFixed(2);toast('Plato añadido')};$('#cartBtn').onclick=()=>toast(state.cart.length?'Pedido listo para enviar':'Aún no has añadido platos');$('#shareBtn').onclick=()=>navigator.share?navigator.share({title:$('#restaurantName').textContent,url:location.href}):navigator.clipboard?.writeText(location.href).then(()=>toast('Enlace copiado'));
$('#saveAppearance').onclick=async()=>{const payload={name:$('#nameInput').value.trim(),description:$('#metaInput').value.trim(),primaryColor:$('#colorInput').value};try{state.menu={...state.menu,...payload};if(API)await api('/admin/menu',{method:'PATCH',body:JSON.stringify(payload)});renderPublic();toast('Cambios guardados')}catch{toast('No se pudo guardar')}};$('#newDishBtn').onclick=async()=>{const name=prompt('Nombre del plato');if(!name?.trim())return;const price=prompt('Precio (S/)');const d={name:name.trim(),price:Number(price||0),available:true,category:'General'};try{const saved=API?await api('/admin/dishes',{method:'POST',body:JSON.stringify(d)}):{...d,id:crypto.randomUUID()};state.dishes.push(saved);renderAdmin();renderPublic();toast('Plato creado')}catch{toast('No se pudo crear')}};$('#newPromoBtn').onclick=()=>toast('Configura promociones desde tu cuenta conectada');$('#copyLink').onclick=()=>navigator.clipboard?.writeText(location.href).then(()=>toast('Enlace copiado'));$('#dishAdminList').onchange=async e=>{if(!e.target.dataset.dish)return;const d=state.dishes.find(x=>x.id===e.target.dataset.dish);d.available=e.target.checked;try{if(API)await api('/admin/dishes/'+encodeURIComponent(d.id),{method:'PATCH',body:JSON.stringify({available:d.available})});renderPublic();toast('Disponibilidad actualizada')}catch{toast('No se pudo actualizar')}};load();

// GitHub Pages mode: functional local-first admin. Cloud API takes precedence when configured.
if(!API){
  const localRenderAdmin=renderAdmin;
  renderAdmin=function(){
    localRenderAdmin();
    $('#dishAdminList').querySelectorAll('.dish-admin').forEach((row,index)=>{
      const actions=document.createElement('div');actions.className='dish-actions';
      actions.innerHTML=`<button class="admin-action" data-edit="${index}" aria-label="Editar plato">✎</button><button class="admin-action" data-delete="${index}" aria-label="Eliminar plato">×</button>`;
      row.append(actions);
    });
    const publicUrl=location.origin+location.pathname;
    $('#qrText').textContent=publicUrl;
    $('#qrCode').src='https://api.qrserver.com/v1/create-qr-code/?size=320x320&data='+encodeURIComponent(publicUrl);
  };
  $('#adminToggle').onclick=()=>{$('#publicView').classList.toggle('hidden');$('#adminView').classList.toggle('hidden');if(!$('#adminView').classList.contains('hidden')){sessionStorage.setItem('suya_session','local');openAdmin()}};
  $('#logoutBtn').onclick=()=>{$('#adminView').classList.add('hidden');$('#publicView').classList.remove('hidden')};
  $('#saveAppearance').onclick=()=>{state.menu={...(state.menu||{}),name:$('#nameInput').value.trim(),description:$('#metaInput').value.trim(),primaryColor:$('#colorInput').value,fontFamily:$('#fontInput').value};persist();renderPublic();renderAdmin();toast('Cambios guardados en este dispositivo')};
  $('#newDishBtn').onclick=()=>$('#dishDialog').showModal();
  $('#newPromoBtn').onclick=()=>$('#promoDialog').showModal();
  document.querySelectorAll('[data-close]').forEach(button=>button.onclick=()=>$('#'+button.dataset.close).close());
  $('#dishForm').onsubmit=event=>{event.preventDefault();const price=Number($('#dishPrice').value);if(!Number.isFinite(price)||price<0){toast('Precio inválido');return}const saveDish=imageUrl=>{state.dishes.push({id:crypto.randomUUID(),name:$('#dishName').value.trim(),description:$('#dishDescription').value.trim(),price,category:$('#dishCategory').value.trim()||'General',imageUrl,available:true});persist();renderAdmin();renderPublic();$('#dishDialog').close();event.target.reset();$('#dishCategory').value='General';toast('Plato creado')};const file=$('#dishImage').files?.[0];if(!file){saveDish('');return}if(file.size>1500000){toast('Imagen máxima: 1.5 MB');return}const reader=new FileReader();reader.onload=()=>saveDish(reader.result);reader.readAsDataURL(file)};
  $('#promoForm').onsubmit=event=>{event.preventDefault();state.promos.push({id:crypto.randomUUID(),name:$('#promoName').value.trim(),code:$('#promoCode').value.trim()});persist();renderAdmin();$('#promoDialog').close();event.target.reset();toast('Promoción creada')};
  $('#dishAdminList').onclick=e=>{const edit=e.target.dataset.edit,del=e.target.dataset.delete;if(edit!==undefined){const dish=state.dishes[Number(edit)];const name=prompt('Nombre',dish.name);if(name?.trim())dish.name=name.trim();const price=prompt('Precio',dish.price);if(price!==null&&Number.isFinite(Number(price)))dish.price=Number(price);persist();renderAdmin();renderPublic()}if(del!==undefined&&confirm('¿Eliminar este plato?')){state.dishes.splice(Number(del),1);persist();renderAdmin();renderPublic()}};
  $('#dishAdminList').onchange=e=>{if(!e.target.dataset.dish)return;const dish=state.dishes.find(item=>item.id===e.target.dataset.dish);if(dish){dish.available=e.target.checked;persist();renderPublic();toast('Disponibilidad actualizada')}};
  const readImage=(input,key,target,text)=>input.addEventListener('change',()=>{const file=input.files?.[0];if(!file)return;if(file.size>1500000){toast('Imagen máxima: 1.5 MB');input.value='';return}const reader=new FileReader();reader.onload=()=>{state.menu={...(state.menu||{}),[key]:reader.result};persist();target.style.backgroundImage=`url("${reader.result}")`;target.textContent=text||'';toast('Imagen guardada')};reader.readAsDataURL(file)});
  readImage($('#logoInput'),'logoUrl',$('#logo'),'');readImage($('#coverInput'),'coverUrl',$('#cover'),'');
  $('#copyLink').onclick=()=>navigator.clipboard.writeText(location.origin+location.pathname).then(()=>toast('Enlace copiado'));
}
